name: nanovdb_editor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - gxx_linux-64  # [linux]
  - libstdcxx-ng  # [linux]
  - scikit-build-core
  - pytest
  - parameterized
  - black
  - ninja
