name: NanoVDB Editor Publish

# Intended workflow to release new version:
# - prepare your changes on develop branch
# - manually trigger workflow_dispatch to build and publish to test PyPi when version is bumped
# - test the new package
# - merge develop to main when happy with changes
# - push new version tag to trigger publish to prod PyPi

on:
  push:
    tags:
      - 'v*'
  #   branches:
  #     - develop
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build wheels and sdist
    uses: ./.github/workflows/build-wheels.yml
    with:
      is_dev_package: false
      allow_dev_suffix: false

  # Test upload from develop branch
  upload_test_pypi:
    name: Upload wheel to test PyPi
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: "*"
        merge-multiple: true
        path: dist/

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        verbose: true
        skip-existing: true

  # Production upload for version tags
  upload_pypi:
    name: Upload wheel to PyPi
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-dev') && needs.build.outputs.version_valid == 'true'

    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: "*"
        merge-multiple: true
        path: dist/

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
