name: Build and test Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
        - 'CODEOWNERS'
        - '**.md'
        - 'dev_utils/**'
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "main"

# Allow subsequent pushes to the same PR or REF to cancel any previous jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  deployments: write
  pull-requests: read
  issues: read

jobs:
  nanovdb-editor-build-python-linux:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    name: NanoVDB Editor Build Python (Linux)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Vulkan Loader dependencies
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y libxcb1-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-xinerama0-dev libx11-xcb-dev libxrandr-dev libwayland-dev wayland-protocols libdirectfb-dev

      - name: Build NanoVDB Editor Python module
        run: |
          set -e
          chmod +x ./build.sh
          ./build.sh -pv

      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nanovdb-editor-wheel
          path: |
            pymodule/dist/
          retention-days: 2

      - name: Set up Python environment
        run: |
          set -e
          python -m pip install numpy
          sudo apt-get update
          sudo apt-get install -y mesa-vulkan-drivers vulkan-tools

      - name: Build NanoVDB Editor C tests
        run: |
          set -e
          cd pymodule/test_c
          chmod +x ./build.sh
          ./build.sh

      # Integration tests for the python module

      - name: Run NanoVDB Editor C tests
        run: |
          set -e
          cd pymodule/test_c
          if [ -f "build/pnanovdbeditortestcapp" ]; then
            echo "Running C tests..."
            chmod +x ./build/pnanovdbeditortestcapp
            ./build/pnanovdbeditortestcapp
          else
            echo "No C test application found"
          fi

      - name: Build C++ Python module test
        run: |
          set -e
          cd pymodule/test_cpp
          chmod +x ./build.sh
          ./build.sh

  nanovdb-editor-test-python-linux:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    name: NanoVDB Editor Test Python (Linux)
    needs: nanovdb-editor-build-python-linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda env
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          conda-remove-defaults: "true"
          activate-environment: nanovdb_editor
          environment-file: pymodule/dev_environment.yml

      - name: Install Vulkan runtime (headless)
        run: |
          conda activate nanovdb_editor
          sudo apt-get update
          sudo apt-get install -y mesa-vulkan-drivers vulkan-tools

      - name: Download package with nanovdb_editor
        uses: actions/download-artifact@v4
        with:
          name: nanovdb-editor-wheel
          path: ./dist

      - name: Install nanovdb_editor
        run: |
          conda activate nanovdb_editor
          pip install ./dist/nanovdb_editor*.whl

      - name: Run Python tests
        run: |
          conda activate nanovdb_editor
          pytest -vvv
